matrix:
    include:
        - python: 3.6
          env: TOXENV=py36
        - python: 3.8
          env: TOXENV=py38
language: python
install:
  - pip install tox coveralls
script:
  - tox
  - tox -e coverage
after_success:
  - coveralls
